import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Placa Mãe ASUS Prime B450M-A",
    description: "Placa mãe AMD AM4 com suporte para processadores Ryzen, DDR4, USB 3.1 e M.2",
    price: 699.9,
    originalPrice: 899.9,
    discount: 22,
    category: "motherboard",
    brand: "ASUS",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
    inStock: true,
    stockQuantity: 15,
    specifications: {
      Socket: "AM4",
      Chipset: "B450",
      Memória: "DDR4",
      "Slots de RAM": "4",
      "Máximo de RAM": "128GB",
    },
    rating: 4.5,
    reviews: [],
  },
  {
    id: "2",
    name: "SSD Kingston NV2 1TB M.2",
    description: "SSD NVMe PCIe 4.0 de alta performance para jogos e aplicações profissionais",
    price: 349.9,
    originalPrice: 449.9,
    discount: 22,
    category: "storage",
    brand: "Kingston",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    inStock: true,
    stockQuantity: 25,
    specifications: {
      Capacidade: "1TB",
      Interface: "M.2 NVMe PCIe 4.0",
      "Velocidade de Leitura": "3.500 MB/s",
      "Velocidade de Escrita": "2.100 MB/s",
    },
    rating: 4.7,
    reviews: [],
  },
  {
    id: "3",
    name: "Processador Intel Core i5-12400F",
    description: "Processador Intel de 12ª geração com 6 núcleos e 12 threads, ideal para gaming",
    price: 999.9,
    originalPrice: 1299.9,
    discount: 23,
    category: "processor",
    brand: "Intel",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    inStock: true,
    stockQuantity: 8,
    specifications: {
      Núcleos: "6",
      Threads: "12",
      "Frequência Base": "2.5 GHz",
      "Frequência Turbo": "4.4 GHz",
      Socket: "LGA1700",
    },
    rating: 4.8,
    reviews: [],
  },
  {
    id: "4",
    name: "Placa de Vídeo RTX 4060 Ti 16GB",
    description: "Placa de vídeo NVIDIA GeForce RTX 4060 Ti com 16GB GDDR6 e Ray Tracing",
    price: 2399.9,
    originalPrice: 2899.9,
    discount: 17,
    category: "graphics-card",
    brand: "NVIDIA",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    inStock: true,
    stockQuantity: 5,
    specifications: {
      Memória: "16GB GDDR6",
      Interface: "PCIe 4.0",
      "CUDA Cores": "4352",
      "Ray Tracing": "Sim",
      DLSS: "3.0",
    },
    rating: 4.9,
    reviews: [],
  },
  {
    id: "5",
    name: "Memória RAM DDR4 16GB 3200MHz",
    description: "Kit de memória DDR4 16GB (2x8GB) 3200MHz para alta performance",
    price: 299.9,
    originalPrice: 399.9,
    discount: 25,
    category: "memory",
    brand: "Corsair",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    inStock: true,
    stockQuantity: 30,
    specifications: {
      Capacidade: "16GB (2x8GB)",
      Tipo: "DDR4",
      Frequência: "3200MHz",
      Latência: "CL16",
      Voltagem: "1.35V",
    },
    rating: 4.6,
    reviews: [],
  },
  {
    id: "6",
    name: "Placa de Vídeo GeForce RTX 4070 12GB",
    description: "Placa de vídeo NVIDIA GeForce RTX 4070 com 12GB GDDR6X e tecnologia Ada Lovelace",
    price: 2999.9,
    originalPrice: 3499.9,
    discount: 14,
    category: "graphics-card",
    brand: "NVIDIA",
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    inStock: true,
    stockQuantity: 3,
    specifications: {
      Memória: "12GB GDDR6X",
      Interface: "PCIe 4.0",
      "CUDA Cores": "5888",
      "Ray Tracing": "Sim",
      DLSS: "3.0",
    },
    rating: 4.8,
    reviews: [],
  },
]

export const categories = [
  { id: "processor", name: "Processadores", icon: "🔧" },
  { id: "graphics-card", name: "Placas de Vídeo", icon: "🎮" },
  { id: "motherboard", name: "Placas Mãe", icon: "💻" },
  { id: "memory", name: "Memórias", icon: "🧠" },
  { id: "storage", name: "Armazenamento", icon: "💾" },
  { id: "cooling", name: "Refrigeração", icon: "❄️" },
  { id: "power-supply", name: "Fontes", icon: "⚡" },
  { id: "case", name: "Gabinetes", icon: "📦" },
]
